DATA:
    ROOT: 'root path'
    TRAIN_FILE: './video_labels/train_feat_new256_0.txt'
    VAL_FILE: './video_labels/val_feat_new256_with_3id_0.txt'
    DATASET: my_dataset
    NUM_FRAMES: 24
    NUM_CLASSES: 256
    LABEL_LIST: 'labels/mylabels_tmp.csv'
MODEL:
    ARCH: ViT-L/14
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 16
    LR: 1.e-6
    WARMUP_EPOCHS: 5
    EPOCHS: 35
    START_EPOCH: -1
TEST:
    ONLY_TEST: False
PRINT_FREQ: 1