DATA:
    ROOT: 'root path'
    TRAIN_FILE: './video_labels/train_feat_new256_0.txt'
    VAL_FILE: './video_labels/explain_list.txt'
    DATASET: my_dataset
    NUM_FRAMES: 24
    NUM_CLASSES: 256
    LABEL_LIST: 'labels/mylabels_tmp.csv'
MODEL:
    ARCH: ViT-L/14
TRAIN:
    BATCH_SIZE: 1
    ACCUMULATION_STEPS: 16
    LR: 1.e-6
    WARMUP_EPOCHS: 5
    EPOCHS: 30
    ONLY_FINETUNE: True
TEST:
    ONLY_TEST: False
    EXPLAIN: True
    EXPLAIN_NUM: 1
    TOP_X: 2
    TOP_X_PIXEL_NUM: 20
PRINT_FREQ: 1